import javax.swing.*;

/**
 *
 *
 *                  +-------------------------------------------+
 *                  |                  ***                      |
 *                  |       ***   Darth C0mp1ler   ***          |
 *                  |                  ***                      |
 *                  +-------------------------------------------+
 *
 *
 * Project I
 * Your task is to create a desktop application, that combines 2 parts:
 *
 * Painting module
 * Module consists of main window, which generates primitive shaped elements (ellipses,
 * rectangles, triangles, etc.) with different colors, locations and dimensions.
 * At constant intervals, there is a new element added (drawn), which values are pseudorandom.
 * The element has to have a proper location and dimension, so it fits in the window.
 * Resizing a window is followed by rescaling all drawn elements.
 * Program has to save information about generated shapes to a file.
 *
 * Displaying module
 * It consists of a window, which reads information about shapes from a file and draws
 * them in the window. Generated image has to be the same as the one generated by painting module.
 * Resizing a window is followed by rescaling all drawn elements.
 *
 * Additional description
 * Modules are understood as two parts of an application. It does not implicate
 * necessity of using modules or packages available by Java language.
 *
 * Format of a saved file is determined by a student. One cannot use “Object Streams” classes.
 */

public class Main {

    static int shapesQuantity;

    public static void main(String[] args) {
        shapesQuantity = 25;
        SwingUtilities.invokeLater(
                () -> new Main()
        );
    }

    public Main() {
        RandomizeShapes randomizeShapes = new RandomizeShapes();
        JFrame fr = new JFrame("CREATE");
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.add(randomizeShapes);
        fr.setLocation(0,0);
        fr.setVisible(true);
        fr.pack();




    }
}

